name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature-login-page
  pull_request:
    branches:
      - main

jobs:
  test:
    runs ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check index.html exists
        run: test -f index.html

      - name: Check style.css exists
        run: test -f style.css

      - name: Simulate validation test
        run: echo "All CI checks passed successfully."